export enum ACTIONS {
    ADD_CATEGORY = 'ADD_CATEGORY',
    ADD_CATEGORY_INTO_CATEGORY = 'ADD_CATEGORY_INTO_CATEGORY',
    EDIT_CATEGORY = 'EDIT_CATEGORY',
    DELETE_CATEGORY = 'DELETE_CATEGORY',
    ADD_TODO_ITEM = 'ADD_TODO_ITEM',
    EDIT_TODO_ITEM = 'EDIT_TODO_ITEM',
    MARK_AS_DONE_ITEM = 'MARK_AS_DONE_ITEM',
    MOVE_TODO_ITEM = 'MOVE_TODO_ITEM',
    SAVE_CURRENT_ID = 'SAVE_CURRENT_ID',
    CHECK_PROGRESS = 'CHECK_PROGRESS',
    SET_CATEGORY_EDITABLE = 'SET_CATEGORY_EDITABLE',
    SET_FILTER_TODO_ITEMS = 'SET_FILTER_TODO_ITEMS',
    SET_CATEGORY_EXPANDED = 'SET_CATEGORY_EXPANDED',
    SET_SEARCH_FILTER = 'SET_SEARCH_FILTER',
    SET_CURRENT_TODO_ITEM = 'SET_CURRENT_TODO_ITEM',
    SET_TODO_CATEGORY ='SET_TODO_CATEGORY'


}